### ISSUE TITLE
La aplicación no se arranca en MacOS Catalina 10.15.1

### ISSUE THREAD

**Issue by AlberGonAcosta** [alexfp95/Survival-Maze#1]
Básicamente, como indica el título, la aplicación no puede abrirse en MacOS Catalina 10.15.1. Al intentar abrir el ejecutable aparece una ventana con el mensaje "La aplicación 'SurvivalMaze' no se puede abrir".

Adicionalmente, en la configuración de Seguridad y privacidad del dispositivo se ha comprobado que se permite la ejecución de apps descargadas de "App Store y desarrolladores identificados"

**Comment by alexfp95** [comment]
This is an issue that happens in Catalina.

To solve it, do the following steps:
- Right-click on the executable
- Show Package Content
- Go to Contents/MacOS
- Here you'll see SurvivalMaze file. 
- Just give him exec permission with the command tool: chmod +x SurvivalMaze
